"""add constraints and indexes

Revision ID: a207c1b7252d
Revises: 59e6d8214af1
Create Date: 2026-02-25 20:29:06.861878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a207c1b7252d'
down_revision: Union[str, Sequence[str], None] = '59e6d8214af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_ecu_vehicle_name', 'ecus', ['vehicle_id', 'name'])
    op.create_index('ix_events_ecu_created', 'events', ['ecu_id', 'created_at'], unique=False)
    op.create_index('ix_events_vehicle_created', 'events', ['vehicle_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_vehicle_created', table_name='events')
    op.drop_index('ix_events_ecu_created', table_name='events')
    op.drop_constraint('uq_ecu_vehicle_name', 'ecus', type_='unique')
    # ### end Alembic commands ###
